# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Snoopyo Search
email: info@snoopyo.com
description: >- # this means to ignore newlines until "baseurl:"
  Most powerful and bleazingly fast search engin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "snoopyo.com" # the base hostname & protocol for your site, e.g. http://example.com
policy_url: "https://snoopyo.com/policies" # the base hostname & protocol for your site, e.g. http://example.com

newsletter:
  type: primary # [default, primary]
  message: Subscribe our newsletter to receive the latest news and exclusive offers.
  placeholder: Please Enter Your Email
  btn_text: SUBSCRIBE
repository: "snoopyo/blog"
# Build settings

markdown: kramdown
highlighter: rouge

show_excerpts: true
disqus: snoopyo
paginate: 1
date_format: "%b %-d, %Y"
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
